
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master


strategy:
  matrix:
    linux_net8:
      imageName: 'ubuntu-latest'
      dotnetVersion: '8.x'
    linux_net9:
      imageName: 'ubuntu-latest'
      dotnetVersion: '9.x'

    mac_net8:
      imageName: 'macOS-latest'
      dotnetVersion: '8.x'
    mac_net9:
      imageName: 'macOS-latest'
      dotnetVersion: '9.x'

    windows_net8:
      imageName: 'windows-latest'
      dotnetVersion: '8.x'
    windows_net9:
      imageName: 'windows-latest'
      dotnetVersion: '9.x'

  maxParallel: 3


pool:
  vmImage: $(imageName)


variables:
  buildConfiguration: 'Release'


steps:


- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetVersion)'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'


- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test (with XPlat Code Coverage)'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
    publishTestResults: true

- task: PublishCodeCoverageResults@2
  displayName: 'Publish code coverage results'
  inputs:
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
    failIfCoverageEmpty: false
